version: "3.9"
services:
  app:
    #image: node:12.13-alpine
    #working_dir: /app

    # Important to send volumes instead of making Volume in Dockerfile
    volumes:
     - .:/app
     - /app/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
      target: "${NODE_ENV}"
    ports:
      - ${PORT}:${PORT}
    environment: 
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    #command: sh -c "npm install && npm run start:dev"
    networks:
      - backend
    depends_on:
      - db
  redis:
    image: "redis:alpine"
    networks: 
      - backend
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      #MYSQL_ROOT_HOST: '%'
    volumes:
      - data1:/var/lib/mysql
    networks:
      - backend
networks:
  backend: 
volumes: 
  data1: {}
  notused: 